BEGIN TRANSACTION;
DROP TABLE IF EXISTS "maher_users";
CREATE TABLE IF NOT EXISTS "maher_users" (
	"id"	INTEGER PRIMARY KEY AUTOINCREMENT,
	"name"	VARCHAR NOT NULL,
	"username"	VARCHAR NOT NULL UNIQUE,
	"email"	VARCHAR NOT NULL UNIQUE,
	"password"	VARCHAR NOT NULL,
	"created_at"	TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
DROP TABLE IF EXISTS "maher_albums";
CREATE TABLE IF NOT EXISTS "maher_albums" (
	"id"	INTEGER PRIMARY KEY AUTOINCREMENT,
	"title"	VARCHAR NOT NULL,
	"description"	VARCHAR NOT NULL,
	"cover_image"	INTEGER NOT NULL,
	"created_at"	TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"user_id"	INTEGER
);
DROP TABLE IF EXISTS "maher_images";
CREATE TABLE IF NOT EXISTS "maher_images" (
	"id"	INTEGER PRIMARY KEY AUTOINCREMENT,
	"image_url"	VARCHAR NOT NULL UNIQUE,
	"title"	VARCHAR NOT NULL,
	"album_id"	INTEGER NOT NULL,
	"created_at"	TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMIT;
